[versions]
junit = "5.9.2"
log4j = "2.20.0"
jline = "3.22.0"
fastutil = "8.5.3"

[libraries]
protocol = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version = "3.0.0.Beta1-SNAPSHOT" }

fastutil-long-common = { group = "com.nukkitx.fastutil", name = "fastutil-long-common", version.ref = "fastutil" }
fastutil-long-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-long-object-maps", version.ref = "fastutil" }
fastutil-long-long-maps = { group = "com.nukkitx.fastutil", name = "fastutil-long-long-maps", version.ref = "fastutil" }
fastutil-long-int-maps = { group = "com.nukkitx.fastutil", name = "fastutil-long-int-maps", version.ref = "fastutil" }
fastutil-int-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-int-object-maps", version.ref = "fastutil" }
fastutil-object-int-maps = { group = "com.nukkitx.fastutil", name = "fastutil-object-int-maps", version.ref = "fastutil" }
fastutil-int-int-maps = { group = "com.nukkitx.fastutil", name = "fastutil-int-int-maps", version.ref = "fastutil" }

guava = { group = "com.google.guava", name = "guava", version = "30.1.1-jre" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version = "1.33" }
leveldb = { group = "org.iq80.leveldb", name = "leveldb", version = "0.11-SNAPSHOT" }
jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version = "9.13" }
jopt-simple = { group = "net.sf.jopt-simple", name = "jopt-simple", version = "5.0.4" }
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.26" }

# Logging dependencies
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }

# CLI dependencies
jline-terminal = { group = "org.jline", name = "jline-terminal", version.ref = "jline" }
jline-terminal-jna = { group = "org.jline", name = "jline-terminal-jna", version.ref = "jline" }
jline-reader = { group = "org.jline", name = "jline-reader", version.ref = "jline" }
terminal-console = { group = "net.minecrell", name = "terminalconsoleappender", version = "1.3.0"}

# Testing dependencies
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

[bundles]
log4j = [ "log4j-api", "log4j-core" ]
terminal = [ "jline-terminal", "jline-terminal-jna", "jline-reader", "terminal-console" ]
junit = [ "junit-jupiter-api", "junit-jupiter-engine" ]
fastutil = [ "fastutil-long-common", "fastutil-long-object-maps", "fastutil-long-long-maps", "fastutil-long-int-maps",
    "fastutil-int-object-maps", "fastutil-object-int-maps", "fastutil-int-int-maps" ]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.0.0" }
git = { id = "com.gorylenko.gradle-git-properties", version = "2.4.1" }
